dangphung4/Leaflet

- .github/workflows/commit-lint.yaml
> ci: add back commit-lint in correct repo

- .github/workflows/commit-lint.yaml
> ci: fix commit lint not pulling on requests

- notes/src/App.tsx
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/Home.tsx
- notes/src/Core/Theme/ThemeProvider.tsx
> feat: update theme provider and home page to match repo

- .cursorrules
- README.md
- notes/src/App.tsx
- notes/src/Core/Components/Editor.tsx
- notes/src/Core/Components/TemplateDialog.tsx
- notes/src/Core/Components/navbar.tsx
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/EditNote.tsx
- notes/src/Core/Pages/NewNote.tsx
- notes/src/Core/Pages/Notes.tsx
- notes/src/Core/Theme/ThemeProvider.tsx
- notes/src/components/TagSelector.tsx
> feat: update UI on new notes, edit note, and template dialog

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DEVELOPMENT.md
- TROUBLESHOOTING.md
> docs: add documentation for onboarding and contributing

- notes/globals.css
- notes/src/Core/Components/Editor.tsx
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/Calendar.tsx
- notes/src/Core/Pages/Home.tsx
- notes/src/Core/Pages/NewNote.tsx
- notes/src/Core/Pages/Notes.tsx
- notes/src/Core/Pages/Profile.tsx
- notes/src/Core/Theme/ThemeProvider.tsx
> feat: general improvements with fonts, theme, home page , note details and sharing

- notes/src/Core/Components/Editor.tsx
- notes/src/Core/Pages/Home.tsx
> feat: update home page UI integration to be more user friendly

- notes/src/Core/Components/Editor.tsx
> fix: tool tip colors not loading on editor

- notes/src/Core/Pages/Folders.tsx
> feat: update mobile UI on folders page

- README.md
- notes/package-lock.json
- notes/package.json
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/Folders.tsx
> feat: enhanced folders page and toolbar

- notes/globals.css
- notes/package-lock.json
- notes/package.json
- notes/src/Core/Components/NoteTemplates.ts
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/Folders.tsx
- notes/src/Core/Pages/NewNote.tsx
- notes/src/Core/Pages/Profile.tsx
- notes/src/Core/Theme/ThemeProvider.tsx
- notes/src/components/ui/slider.tsx
> feat: font sizing and update note templates

- notes/src/App.tsx
- notes/src/Core/Database/db.ts
- notes/src/Core/Pages/Calendar.tsx
- notes/src/Core/Pages/Folders.tsx
{Detail}
___
- Introduced `FooterWrapper` component to conditionally render the footer based on the current route.
- Enhanced the `NotesDB` class to support new event properties and improve event syncing logic.
- Improved the `Calendar` component with better loading states and event rendering.
- Updated folder and note UI to differentiate between folder and note types visually.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>App.tsx</strong><dd><code>Conditional Footer Rendering in App Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
notes/src/App.tsx
<li>Added …
> feat: calendar agenda improvements and UI changes

- notes/src/Core/Pages/Calendar.tsx
> fix: ui not working well on mobile in calendar edit/create page

- .github/commitlintrc.json
{Detail}
___
- Enhanced the commit message linting configuration by adding new types.
- Improved the overall commit message validation rules.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>commitlintrc.json</strong><dd><code>Enhance commit message linting configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/commitlintrc.json
<li>Added new commit message types: <code>[penify]:</code> and <code>[Penify]:</code><br> <li> Updated configuration for commit message linting<br>
</details>
</td>
<td><a href="https://github.com/dangphung4/Notes/pull/70/files#diff- …
> ci: Update commitlintrc.json

- .github/workflows/commit-lint.yaml
{Detail}
___
- Enhanced the commit linting process for pull requests by checking only the relevant commits.
- Simplified the logic for pushes to check only the latest commit.
- Removed redundant checks for the number of commits in the PR.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>commit-lint.yaml</strong><dd><code>Improve commit linting for pull requests and pushes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/commit-lint.yaml
<li>Updated commit linting logic for pull requests.<br> <li> Simplified the commit range check for pushes.<br> <li> Removed unnecessary conditional checks for commit …
> ci: update commit-lint.yaml

- notes/src/Core/Pages/Notes.tsx
> chore: add back ability to edit folder link in exist notes

- notes/src/Core/Components/ImportDialog.tsx
> feat: persistence in google client token

- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
> docs: update documentation for google oauth

- notes/src/App.tsx
- notes/src/main.tsx
> chore: move auth provider to root level

- notes/src/Core/Pages/EditNote.tsx
- notes/src/Core/Pages/Folders.tsx
- notes/src/Core/Pages/Notes.tsx
> fix: apply fixes based on andrews feedback

- notes/src/Core/Components/Editor.tsx
{Detail}
___
- Commented out the import for `@blocknote/shadcn/style.css` to prevent loading unnecessary styles.
- Ensured that the font styles from `@blocknote/core/fonts/inter.css` remain active.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Editor.tsx</strong><dd><code>Update CSS Imports in Editor Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
notes/src/Core/Components/Editor.tsx
<li>Commented out the import statement for <code>@blocknote/shadcn/style.css</code>.<br> <li> Retained the import for …
> chore: update Editor.tsx css

- notes/src/Core/Pages/EditNote.tsx
> feat: update convert to docx

- notes/src/Core/Pages/EditNote.tsx
> fix: pdf converter

- notes/src/Core/Pages/Home.tsx
> chore: Update Home.tsx
